import type { Metadata } from "next";

import Header from "./header/header";

import '../../public/css/style.css'
import Footer from "./footer/footer";

export const metadata: Metadata = {
  title: "Criando Layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <main>
        <Header />
        {children}
        <Footer />
      </main>
      </body>
    </html>
  );
}
