import type { Metadata } from "next";
import Header from "./header/header";
import Footer from "./footer/footer";
import '../../public/css/style.css';


export const metadata: Metadata = {
  title: "Site_Restaurantes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <main>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
